const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
const DEACTIVATE_CUSTOMER = 'DEACTIVATE_CUSTOMER'
const REACTIVATE_CUSTOMER = 'REACTIVATE_CUSTOMER'

export {
  CREATE_CUSTOMER,
  UPDATE_CUSTOMER,
  DEACTIVATE_CUSTOMER,
  REACTIVATE_CUSTOMER
}