const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
const DEACTIVATE_CUSTOMER = 'DEACTIVATE_CUSTOMER'

export {
  CREATE_CUSTOMER,
  UPDATE_CUSTOMER,
  DEACTIVATE_CUSTOMER
}