const CUSTOMER_CREATED = 'CUSTOMER_CREATED'
const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
const CUSTOMER_DEACTIVATED = 'CUSTOMER_DEACTIVATED'

export {
  CUSTOMER_CREATED,
  CUSTOMER_UPDATED,
  CUSTOMER_DEACTIVATED
}