const CUSTOMER_REGISTERED = 'CUSTOMER_REGISTERED'
const CUSTOMER_CREATED = 'CUSTOMER_CREATED'
const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
const CUSTOMER_DEACTIVATED = 'CUSTOMER_DEACTIVATED'
const CUSTOMER_REACTIVATED = 'CUSTOMER_REACTIVATED'

const CUSTOMER_EXISTING_EMAIL_FOUND = 'CUSTOMER_EXISTING_EMAIL_FOUND'

export {
  CUSTOMER_REGISTERED,
  CUSTOMER_CREATED,
  CUSTOMER_UPDATED,
  CUSTOMER_DEACTIVATED,
  CUSTOMER_REACTIVATED,
  CUSTOMER_EXISTING_EMAIL_FOUND
}